name: 🛠️ Setup
description: Checkout the repository, set up Deno, optionally set up Node.js, and install dependencies.
inputs:
  node:
    description: Whether to also set up Node.js
    required: false
    default: 'false'
runs:
  using: composite
  steps:
    - name: 🦕 Setup Deno
      uses: denoland/setup-deno@22d081ff2d3a40755e97629de92e3bcbfa7cf2ed # v2.0.5
      with:
        deno-version: v2.x
        cache: true

    - name: 🟢 Setup Node.js
      if: inputs.node == 'true'
      uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
      with:
        node-version: lts/*
        registry-url: 'https://registry.npmjs.org'

    - name: 📥 Install dependencies
      shell: bash
      run: deno install
