name: ♾️ CI
permissions:
  contents: read
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - next-major
      - next-minor
      - next-patch
jobs:
  # dry-publish:
  #   name: 📦 Publish (dry run)
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: 📂 Checkout
  #       uses: actions/checkout@v6

  #     - name: 🛠️ Setup
  #       uses: ./.github/actions/setup

  #     - name: 📦 Publish (dry run)
  #       run: deno task publish:npm --dry-run && deno task publish:jsr --dry-run
  publish:
    name: 🚀 Publish
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    # needs: [dry-publish]
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - name: 📂 Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: 🛠️ Setup
        uses: ./.github/actions/setup
        with:
          node: true

      # Project is built and published using @semantic-release/exec
      - name: 🚀 Publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run semantic-release
